export const commands = {
    START:          'start',
    MIRRORTAR:      'mtx|mt',
    MIRROR:         'mirrorx|m',
    MIRROR_STATUS:  'mirrorStatusx|ms',
    LIST:           'listx|l',
    GET_FOLDER:     'getFolder|gf',
    CANCEL_MIRROR:  'cancelMirrorx|cm',
    CANCEL_ALL:     'cancelAllx|ca',
    STATS:          'stats',
    GET_LINK:       'getLink|gl',
    CLONE:          'clone|c',
    ID:             'id',
    MF:             'mf',
    TAR:            'tardrive|t',
    UNZIP_MIRROR:   'unzipMirror|um',
    COUT:           'count|cnt',
    HELP:           'helpx|h',
    AUTHORIZE:      'authorizex|a',
    UNAUTHORIZE:    'unauthorizex|ua',
    RESTART:        'restartx|r',
    YTDL:           'ytdlx|y'
};

export const commandsAfter: any = {
    START:          '$',
    MIRRORTAR:      '($| (.+))',
    MIRROR:         '($| (.+))',
    MIRROR_STATUS:  '$',
    LIST:           ' (.+)',
    GET_FOLDER:     '$',
    CANCEL_MIRROR:  '($| (.+))',
    CANCEL_ALL:     '$',
    STATS:          '$',
    GET_LINK:       ' (.+)',
    CLONE:          ' (.+)',
    ID:             '$',
    MF:             '$',
    TAR:            ' (.+)',
    UNZIP_MIRROR:   ' (.+)',
    COUT:           ' (.+)',
    HELP:           '$',
    AUTHORIZE:      '$',
    UNAUTHORIZE:    '$',
    RESTART:        '$',
    YTDL:           '($| (.+))'
};